### ISSUE TITLE
[BUG] Received an error from node while fetching anomaly grade for _model_rcf_1

### ISSUE THREAD

**Issue by olegchorny** [opendistro-for-elasticsearch/anomaly-detection#135] opened 2020-05-26 00:12 UTC
**Describe the bug**
AD can't fetch the anomaly grade (but works during the preview mode for all functions)

**Other plugins installed**
latest default helm installation (3 data, 2 clients, 2 masters)

**To Reproduce**
1. Cluster installation stage: https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/
2. Cluster security stage https://github.com/opendistro-for-elasticsearch/community/tree/master/open-distro-elasticsearch-kubernetes
3. push data to the cluster and configure detectors using the sum() function 

**Expected behavior**
Detector should be successfully initialized 

**Screenshots**

**Desktop (please complete the following information):**
kubernetes 1.17

**Additional context**
```
[2020-05-25T23:59:24,779][ERROR][c.a.o.a.t.AnomalyResultTransportAction] [opendistro-es-data-0] Received an error from node h_GmpNjVTTeUj9kboAOP7A while fetching anomaly grade for jbQZTnIB0O1bbpIpy6Eh_model_rcf_1
org.elasticsearch.transport.RemoteTransportException: [opendistro-es-data-1][10.100.1.11:9300][cluster:admin/ad/rcf/result]
Caused by: java.lang.IllegalArgumentException
        at java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2295) ~[?:?]
        at java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2165) ~[?:?]
        at com.amazon.randomcutforest.ParallelForestTraversalExecutor.<init>(ParallelForestTraversalExecutor.java:41) ~[?:?]
        at com.amazon.randomcutforest.RandomCutForest.<init>(RandomCutForest.java:184) ~[?:?]
        at com.amazon.randomcutforest.RandomCutForest$Builder.build(RandomCutForest.java:886) ~[?:?]
        at com.amazon.randomcutforest.RandomCutForest.defaultForest(RandomCutForest.java:216) ~[?:?]
        at com.amazon.randomcutforest.serialize.RandomCutForestAdapter.createInstance(RandomCutForestAdapter.java:30) ~[?:?]
        at com.amazon.randomcutforest.serialize.RandomCutForestAdapter.createInstance(RandomCutForestAdapter.java:26) ~[?:?]
        at com.google.gson.internal.ConstructorConstructor$1.construct(ConstructorConstructor.java:68) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:927) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:892) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:841) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:813) ~[?:?]
        at com.amazon.randomcutforest.serialize.RandomCutForestSerDe.fromJson(RandomCutForestSerDe.java:87) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$processRcfCheckpoint$9(ModelManager.java:397) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:310) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$processRcfCheckpoint$10(ModelManager.java:397) ~[?:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.processRcfCheckpoint(ModelManager.java:397) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$getRcfResult$8(ModelManager.java:374) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.6.1.jar:7.6.1]
        at com.amazon.opendistroforelasticsearch.ad.ml.CheckpointDao.lambda$getModelCheckpoint$2(CheckpointDao.java:137) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.6.1.jar:7.6.1]
        at com.amazon.opendistroforelasticsearch.ad.util.ClientUtil.lambda$asyncRequest$2(ClientUtil.java:134) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:261) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:247) ~[elasticsearch-7.6.1.jar:7.6.1]
        at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityInterceptor$RestoringTransportResponseHandler.handleResponse(OpenDistroSecurityInterceptor.java:270) ~[?:?]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1108) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:222) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:214) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:139) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:103) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:667) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [transport-netty4-client-7.6.1.jar:7.6.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478) [netty-handler-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) [netty-handler-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) [netty-handler-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:600) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:554) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-common-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.43.Final.jar:4.1.43.Final]
        at java.lang.Thread.run(Thread.java:835) [?:?]

        
[2020-05-25T23:59:24,784][ERROR][c.a.o.a.AnomalyDetectorJobRunner] [opendistro-es-data-0] EndRunException happened when executing anomaly result action for jbQZTnIB0O1bbpIpy6Eh
com.amazon.opendistroforelasticsearch.ad.common.exception.EndRunException: We might have bugs.
        at com.amazon.opendistroforelasticsearch.ad.transport.AnomalyResultTransportAction.findException(AnomalyResultTransportAction.java:438) ~[opendistro-anomaly-detection-1.7.0.0.jar:1.7.0.0]
        at com.amazon.opendistroforelasticsearch.ad.transport.AnomalyResultTransportAction.handlePredictionFailure(AnomalyResultTransportAction.java:697) ~[opendistro-anomaly-detection-1.7.0.0.jar:1.7.0.0]
        at com.amazon.opendistroforelasticsearch.ad.transport.AnomalyResultTransportAction.access$200(AnomalyResultTransportAction.java:78) ~[opendistro-anomaly-detection-1.7.0.0.jar:1.7.0.0]
        at com.amazon.opendistroforelasticsearch.ad.transport.AnomalyResultTransportAction$RCFActionListener.onFailure(AnomalyResultTransportAction.java:556) [opendistro-anomaly-detection-1.7.0.0.jar:1.7.0.0]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) [elasticsearch-7.6.1.jar:7.6.1]
        at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityInterceptor$RestoringTransportResponseHandler.handleException(OpenDistroSecurityInterceptor.java:276) [opendistro_security-1.7.0.0.jar:1.7.0.0]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1118) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.lambda$handleException$2(InboundHandler.java:244) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:242) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:234) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:137) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:103) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:667) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [transport-netty4-client-7.6.1.jar:7.6.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478) [netty-handler-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) [netty-handler-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) [netty-handler-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281) [netty-codec-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:600) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:554) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-common-4.1.43.Final.jar:4.1.43.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.43.Final.jar:4.1.43.Final]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.IllegalArgumentException
        at java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2295) ~[?:?]
        at java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2165) ~[?:?]
        at com.amazon.randomcutforest.ParallelForestTraversalExecutor.<init>(ParallelForestTraversalExecutor.java:41) ~[?:?]
        at com.amazon.randomcutforest.RandomCutForest.<init>(RandomCutForest.java:184) ~[?:?]
        at com.amazon.randomcutforest.RandomCutForest$Builder.build(RandomCutForest.java:886) ~[?:?]
        at com.amazon.randomcutforest.RandomCutForest.defaultForest(RandomCutForest.java:216) ~[?:?]
        at com.amazon.randomcutforest.serialize.RandomCutForestAdapter.createInstance(RandomCutForestAdapter.java:30) ~[?:?]
        at com.amazon.randomcutforest.serialize.RandomCutForestAdapter.createInstance(RandomCutForestAdapter.java:26) ~[?:?]
        at com.google.gson.internal.ConstructorConstructor$1.construct(ConstructorConstructor.java:68) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:927) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:892) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:841) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:813) ~[?:?]
        at com.amazon.randomcutforest.serialize.RandomCutForestSerDe.fromJson(RandomCutForestSerDe.java:87) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$processRcfCheckpoint$9(ModelManager.java:397) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:310) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$processRcfCheckpoint$10(ModelManager.java:397) ~[?:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.processRcfCheckpoint(ModelManager.java:397) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.lambda$getRcfResult$8(ModelManager.java:374) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.6.1.jar:7.6.1]
        at com.amazon.opendistroforelasticsearch.ad.ml.CheckpointDao.lambda$getModelCheckpoint$2(CheckpointDao.java:137) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.6.1.jar:7.6.1]
        at com.amazon.opendistroforelasticsearch.ad.util.ClientUtil.lambda$asyncRequest$2(ClientUtil.java:134) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:261) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:247) ~[elasticsearch-7.6.1.jar:7.6.1]
        at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityInterceptor$RestoringTransportResponseHandler.handleResponse(OpenDistroSecurityInterceptor.java:270) ~[?:?]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1108) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:222) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:214) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:139) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:103) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:667) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:600) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:554) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) ~[?:?]
[2020-05-25T23:59:24,793][INFO ][c.a.o.a.AnomalyDetectorJobRunner] [opendistro-es-data-0] EndRunException happened for jbQZTnIB0O1bbpIpy6Eh
[2020-05-25T23:59:24,793][INFO ][c.a.o.a.AnomalyDetectorJobRunner] [opendistro-es-data-0] JobRunner will stop AD job due to EndRunException retry exceeds upper limit 3 for jbQZTnIB0O1bbpIpy6Eh
[2020-05-25T23:59:24,813][INFO ][c.a.o.j.s.JobScheduler   ] [opendistro-es-data-0] Descheduling jobId: jbQZTnIB0O1bbpIpy6Eh
[2020-05-25T23:59:24,842][INFO ][c.a.o.a.AnomalyDetectorJobRunner] [opendistro-es-data-0] Released lock for AD job jbQZTnIB0O1bbpIpy6Eh
[2020-05-25T23:59:24,852][INFO ][c.a.o.a.AnomalyDetectorJobRunner] [opendistro-es-data-0] AD Job was disabled by JobRunner for jbQZTnIB0O1bbpIpy6Eh
```

**Comment by olegchorny** [comment] 2020-05-26 11:59
Update: it seems like I didn't allocate enough resources for elasticsearch nodes.
Seems like AD works as expected, if elasticsearch node has 4Gi and 2cpu allocated.

**Comment by wnbts** [comment] 2020-05-26 16:49
We are making a change to prevent such an error. Thanks for reporting this issue.

**Comment by kaituo** [comment] 2020-06-03 23:15
The problem is in this line:
https://github.com/aws/random-cut-forest-by-aws/blob/b827f460991b42accc4af134f6ae2a1077bc34f7/Java/serialization-json/src/main/java/com/amazon/randomcutforest/serialize/RandomCutForestAdapter.java#L30

We create a RCF object, which end up calling the constructor:

https://github.com/aws/random-cut-forest-by-aws/blob/b827f460991b42accc4af134f6ae2a1077bc34f7/Java/core/src/main/java/com/amazon/randomcutforest/RandomCutForest.java#L187

We set parallelExecutionEnabled to false in our de-serialization.  But Gson would first call the new instance creator before setting the properties via reflection.  We are using an old implementation of RCF and the default value of parallelExecutionEnabled is true.  We should update our RCF dependency as Lai has made the change (https://github.com/aws/random-cut-forest-by-aws/pull/34).

So far AD won't work in a computer with only 1 core.

**Comment by wnbts** [comment] 2020-06-17 00:54
The fix has been merged. I am closing this issue.

**Closed by wnbts** 2020-06-17 00:54 UTC
Labels: bug
