### ISSUE TITLE
[BUG] Filter by some strings doesnt bring results

### ISSUE THREAD

**Issue by franco-martin** [opendistro-for-elasticsearch/anomaly-detection#192] opened 2020-07-17 14:54 UTC
**Describe the bug**
No data is returned when filtering by hostname in metricbeat index. 

**Other plugins installed**
Standard odfe kibana 1.9.0 installation

**To Reproduce**
1. Ingest data using metricbeat
2. Create new anomaly detector with metricbeat-* as index pattern and @timestamp as time field. 
3. Use visual editor to add filter. Use field host.name, operator "is", and your hosts value(the one that runs metricbeat)
4. Save changes
5. Add feature with average() of system.cpu.total.pct
6. Click on preview anomalies
7. See message "No sample anomaly result generated..."
8. Validate in discover. 
    a. Go to discover, select metricbeat index pattern
    b. Click add filter
    c. Select host.name as field
    d. Select "is" as operator
    e. Select hostname.
    f. Click save.
    g. See results.

**Expected behavior**
I should be able to see anomalies. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 83.0.4103.116 

**Additional context**
Discover filter section looks like this
```
"filter": [
        {
          "match_all": {}
        },
        {
          "match_phrase": {
            "host.name": "myserver"
          }
        },
        {
          "range": {
            "@timestamp": {
              "gte": "2020-07-17T02:51:14.975Z",
              "lte": "2020-07-17T14:51:14.975Z",
              "format": "strict_date_optional_time"
            }
          }
        }
      ]
```
When changed to custom expression, the filter will look like this
```
"filter": [
            {
                "term": {
                    "host.name": {
                        "value": "myserver",
                        "boost": 1
                    }
                }
            }
        ]
```

**Comment by wnbts** [comment] 2020-07-17 18:49
thanks for using the product and reporting issues. preview results require a sufficient number of data samples over a sufficient period of time. can you visualize the data using the specified filters and bucket size over the last 7 days with kibana? it is possible that there isn't sufficient recent data in the index for preview.

**Comment by franco-martin** [comment] 2020-07-17 18:55
Yes, I have 1.2 million documents in the last 7 days.

**Comment by wnbts** [comment] 2020-07-17 20:18
can you post a screenshot of the filtered data from discovery? so we can compare while reproducing the issue

**Comment by franco-martin** [comment] 2020-07-17 20:33
Here you go. I had to remove the name of the server but it is copy-pasted from the anomaly detector
![Annotation](https://user-images.githubusercontent.com/45946048/87828547-8bb5a700-c853-11ea-8f70-acd71fc96e93.png)

**Comment by wnbts** [comment] 2020-07-17 20:36
thanks so much! that looks good to me. What's the bucket size/detection interval that you use? 1 min? 5 min?

**Comment by franco-martin** [comment] 2020-07-17 20:38
Im running 10 minute detection interval, with a 1 minute delay. ALso tried with a 60minute detection interval but its still the same

**Comment by wnbts** [comment] 2020-07-17 20:58
i suspect filter might be the issue. can you try without filter to narrow down or the following code?

`
    "bool": {
        "filter": [
            {
                "match_phrase": {
                    "host.name": {
                        "query": "myserver"
                    }
                }
            }
        ]
    }
`

**Comment by franco-martin** [comment] 2020-07-17 21:09
Without the filter it works just fine.

**Comment by wnbts** [comment] 2020-07-17 22:56
Great! The issue seems narrowed down to the filter. Does the example filter code work? And if you have access to the es cluster logs, can you find anything interesting?

**Comment by wnbts** [comment] 2020-07-17 23:08
You probably already know that you can use the custom expression option under data filter to update the filter code directly.

**Comment by wnbts** [comment] 2020-07-18 02:08
and what's the date type of the host.name field? keyword? text?

**Comment by franco-martin** [comment] 2020-07-18 19:08
Sorry for the delay. I replicated the environment in my home environment, so I can show you everything without deleting data.
Discovery Data:
![rancher2 discovery](https://user-images.githubusercontent.com/45946048/87860018-2f648d00-c910-11ea-820b-69dd04644afe.PNG)

Tried the visual editor filter, didnt work. Tried your custom expression, didnt work.

The logs show the following exception:
```
Fail to preview anomaly detector n5JLY3MBpzW7Q3PJSN-m
java.lang.IllegalArgumentException: No data to preview anomaly detection.
        at com.amazon.opendistroforelasticsearch.ad.feature.FeatureManager.lambda$getPreviewFeatures$19(FeatureManager.java:348) [opendistro-anomaly-detection-1.9.0.0.jar:1.9.0.0]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.8.0.jar:7.8.0]
        at com.amazon.opendistroforelasticsearch.ad.feature.FeatureManager.lambda$getSamplesForRanges$23(FeatureManager.java:404) [opendistro-anomaly-detection-1.9.0.0.jar:1.9.0.0]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.8.0.jar:7.8.0]
        at com.amazon.opendistroforelasticsearch.ad.feature.SearchFeatureDao.lambda$getFeatureSamplesForPeriods$13(SearchFeatureDao.java:217) [opendistro-anomaly-detection-1.9.0.0.jar:1.9.0.0]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83) [elasticsearch-7.8.0.jar:7.8.0]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.action.PerformanceAnalyzerActionListener.onResponse(PerformanceAnalyzerActionListener.java:60) [opendistro_performance_analyzer-1.9.0.1.jar:1.9.0.1]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:545) [elasticsearch-7.8.0.jar:7.8.0]        at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:117) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:350) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:344) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:231) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:119) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:135) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:47) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695) [elasticsearch-7.8.0.jar:7.8.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.8.0.jar:7.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```
The field is of type string, its not in the index template so I cant confirm but i would say its keyword and text since I get a dropdown from the discovery filter.
![Capture](https://user-images.githubusercontent.com/45946048/87860084-e6610880-c910-11ea-8405-6976a434faf2.PNG)

**Comment by wnbts** [comment] 2020-07-20 16:40
Thanks for the help! The exception shows that the system is unable to find sufficient data.

Let's change the filter back to the original for the detector.

And are you able to visualize the data using 10 minute interval and the term filter and check if there is a data point for every interval?

**Comment by franco-martin** [comment] 2020-07-20 17:28
Im not sure if this is what you request.
![Annotation 2020-07-20 142505](https://user-images.githubusercontent.com/45946048/87967210-e25df380-ca94-11ea-8423-a9ad45e45a40.png)

Is it possible that the fact that when I start writing the name of a field the list doesnt narrow down? it just darkens the matching fields. Also, when using keyword type when filtering in discover you get options, in the anomaly detector you dont. But that might be just a frontend issue.

**Comment by wnbts** [comment] 2020-07-20 18:24
Yes, the plot is what I would like to check and the data stream looks good.

Is it possible for you to share the data (one week of anonymized data is enough) and anomaly detector config so we can try to reproduce it on our side?

**Comment by wnbts** [comment] 2020-07-20 18:28
Actually can you also try to reduce the interval from 10 min to 5 min/1 min? The reason being with 10 min interval, there isn't many data points throughout the day. 5 min or 1 min interval should result into more data points.

**Comment by franco-martin** [comment] 2020-07-20 18:53
Im pretty sure you can replicate it easily. Its just metricbeat data. Have
you tried?

**Comment by wnbts** [comment] 2020-07-20 19:09
I can't replicate it since I don't have the same log data and cannot use metricbeat due to licensing.

**Comment by franco-martin** [comment] 2020-07-20 19:12
im using metricbeat-oss. Does that work? or does it not comply with the
licence?

**Comment by wnbts** [comment] 2020-07-20 19:15
Also, since the issue occurs only when a filter is applied, does it happen to all host names?

**Comment by franco-martin** [comment] 2020-07-20 19:49
I tried aggregating with one minute and 5 minutes with the same result. It does happen with all the hostnames. Some fields do work though. I tested the field "tags" with the operator "is" with a an interval of 10 minutes and it worked.

**Comment by wnbts** [comment] 2020-07-20 19:57
To reproduce this issue, I need to make sure the correct data is used. Are you using the example metricbeat data or data from elsewhere?

**Comment by franco-martin** [comment] 2020-07-20 20:01
Here is my metricbeat file, its all defaults but the ess host.

````
###################### Metricbeat Configuration Example #######################

# This file is an example configuration file highlighting only the most common
# options. The metricbeat.reference.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/index.html

#==========================  Modules configuration ============================

metricbeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression
  #_source.enabled: false

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging


#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here or by using the `setup` command.
#setup.dashboards.enabled: false

# The URL from where to download the dashboards archive. By default this URL
# has a value which is computed based on the Beat name and version. For released
# versions, this URL points to the dashboard archive on the artifacts.elastic.co
# website.
#setup.dashboards.url:

#============================== Kibana =====================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:

  # Kibana Host
  # Scheme and port can be left out and will be set to the default (http and 5601)
  # In case you specify and additional path, the scheme is required: http://localhost:5601/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  #host: "localhost:5601"

  # Kibana Space ID
  # ID of the Kibana Space into which the dashboards should be loaded. By default,
  # the Default Space will be used.
  #space.id:

#============================= Elastic Cloud ==================================

# These settings simplify using metricbeat with the Elastic Cloud (https://cloud.elastic.co/).

# The cloud.id setting overwrites the `output.elasticsearch.hosts` and
# `setup.kibana.host` options.
# You can find the `cloud.id` in the Elastic Cloud web UI.
#cloud.id:

# The cloud.auth setting overwrites the `output.elasticsearch.username` and
# `output.elasticsearch.password` settings. The format is `<user>:<pass>`.
#cloud.auth:

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://elasticsearch:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  username: "admin"
  password: "admin"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]

#============================== Xpack Monitoring ===============================
# metricbeat can export internal metrics to a central Elasticsearch monitoring
# cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
# reporting is disabled by default.

# Set to true to enable the monitoring reporter.
#monitoring.enabled: false

# Uncomment to send the metrics to Elasticsearch. Most settings from the
# Elasticsearch output are accepted here as well.
# Note that the settings should point to your Elasticsearch *monitoring* cluster.
# Any setting that is not set is automatically inherited from the Elasticsearch
# output configuration, so if you have the Elasticsearch output configured such
# that it is pointing to your Elasticsearch monitoring cluster, you can simply
# uncomment the following line.
#monitoring.elasticsearch:

#================================= Migration ==================================

# This allows to enable 6.7 migration aliases
#migration.6_to_7.enabled: true
setup.ilm.enabled: false
````

**Comment by wnbts** [comment] 2020-07-20 21:30
It took some time to figure out xpack from beat. I have one beat running but there is not enough data now. What features are you using?

**Comment by franco-martin** [comment] 2020-07-20 21:33
the default system config.

**Comment by wnbts** [comment] 2020-07-20 21:36
I mean the features in anomaly detector, avg/sum of some fields?

**Comment by franco-martin** [comment] 2020-07-20 21:44
I dont have it handy right now but its average of cpu usage.

**Comment by wnbts** [comment] 2020-07-20 21:53
ok, I am using average system.cpu.total.pct.

**Comment by wnbts** [comment] 2020-07-20 21:59
I attach a plot of the data (from the last hour) on my side. 
![Screenshot from 2020-07-20 14-58-18](https://user-images.githubusercontent.com/57818076/87990814-9ceff500-ca99-11ea-9e32-137ac8548801.png)

**Comment by wnbts** [comment] 2020-07-21 20:53
i am able to reproduce this issue and identify the issue. The system generates incorrect search queries, replacing host.name with host_name. With no matching documents, the result is thus empty.

The next step is to fix the issue and verify the fix.

**Comment by franco-martin** [comment] 2020-07-21 20:58
Great news, let me know if I there is anything else I can do to help.

**Comment by wnbts** [comment] 2020-08-14 22:56
The fix has been merged and I am closing this issue.

**Closed by wnbts** 2020-08-14 22:56 UTC
Labels: bug
