### ISSUE TITLE
Fix Flaky test

### ISSUE THREAD

**Issue by saratvemulapalli** [opendistro-for-elasticsearch/anomaly-detection#254] opened 2020-10-14 19:34 UTC
testSearchResponse in SearchAnomalyDetectorActionTests.java is flaky on Github actions but runs fine on the desktop.

**Comment by kaituo** [comment] 2020-10-16 07:15
Similar error in   SearchAnomalyResultActionTests

2> WARNING: Will linger awaiting termination of 1 leaked thread(s).
  2> com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=314, name=elasticsearch[node_s0][search][T#1], state=RUNNABLE, group=TGRP-SearchAnomalyResultActionTests]

        Caused by:
        java.lang.AssertionError: expected:<2> but was:<5>
            at __randomizedtesting.SeedInfo.seed([1F1AB43F2E4B50C6]:0)
            at org.junit.Assert.fail(Assert.java:88)
            at org.junit.Assert.failNotEquals(Assert.java:834)
            at org.junit.Assert.assertEquals(Assert.java:645)
            at org.junit.Assert.assertEquals(Assert.java:631)
            at com.amazon.opendistroforelasticsearch.ad.transport.SearchAnomalyResultActionTests$1.onResponse(SearchAnomalyResultActionTests.java:48)
            at com.amazon.opendistroforelasticsearch.ad.transport.SearchAnomalyResultActionTests$1.onResponse(SearchAnomalyResultActionTests.java:45)

**Comment by ylwu-amzn** [comment] 2021-01-22 17:59
Refactored search detector action and rewrote the test cases in this PR https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/362
Close this issue.

**Closed by ylwu-amzn** 2021-01-22 17:59 UTC
Labels: bug
